"""
Core account and trading data models for open-nof1.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from pydantic import BaseModel, Field


def _utc_now() -> datetime:
    return datetime.now(tz=timezone.utc)


class Account(BaseModel):
    """Represents the funding state for a single model-managed account."""

    account_id: str
    model_id: str
    base_currency: str = "USD"
    starting_equity: float = Field(..., ge=0)
    cash_balance: float = Field(..., description="Current cash balance in base currency")
    equity: float = Field(..., description="Total account equity including open positions")
    pnl: float = Field(0.0, description="Realized profit and loss since inception")
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)


class Position(BaseModel):
    """Captures an open derivative or spot position held by the account."""

    position_id: str
    account_id: str
    instrument_id: str
    side: str
    quantity: float = Field(..., gt=0)
    entry_price: float = Field(..., gt=0)
    mark_price: Optional[float] = Field(None, gt=0)
    leverage: Optional[float] = Field(None, gt=0)
    unrealized_pnl: Optional[float] = None
    notional_value: Optional[float] = Field(None, ge=0)
    initial_margin: Optional[float] = Field(None, ge=0)
    updated_at: datetime = Field(default_factory=_utc_now)


class Trade(BaseModel):
    """Immutable execution record generated by the trading engines."""

    trade_id: str
    account_id: str
    model_id: str
    instrument_id: str
    side: str
    quantity: float = Field(..., gt=0)
    price: float = Field(..., gt=0)
    close_price: Optional[float] = None
    fee: Optional[float] = None
    realized_pnl: Optional[float] = None
    executed_at: datetime = Field(default_factory=_utc_now)


class ModelSettings(BaseModel):
    """Configurable parameters that tie a model to its managed account."""

    model_id: str
    account_id: str
    description: Optional[str] = None
    max_drawdown_pct: Optional[float] = Field(None, ge=0)
    position_limit_usd: Optional[float] = Field(None, ge=0)
    risk_tier: Optional[str] = None
    updated_at: datetime = Field(default_factory=_utc_now)


class AccountSnapshot(BaseModel):
    """Aggregated representation combining balances, positions, and trades."""

    account: Account
    positions: List[Position] = Field(default_factory=list)
    recent_trades: List[Trade] = Field(default_factory=list)


class Balance(BaseModel):
    """Represents currency-level balance information for an account."""

    balance_id: str
    account_id: str
    currency: str
    total: float = Field(..., ge=0)
    available: float = Field(..., ge=0)
    frozen: float = Field(0.0, ge=0)
    equity: float = Field(0.0, ge=0)
    updated_at: datetime = Field(default_factory=_utc_now)


class Order(BaseModel):
    """Normalized open order representation."""

    order_id: str
    account_id: str
    model_id: str
    instrument_id: str
    side: str
    order_type: str
    size: float = Field(..., ge=0)
    filled_size: float = Field(0.0, ge=0)
    price: Optional[float] = Field(None, ge=0)
    average_price: Optional[float] = Field(None, ge=0)
    state: str = "live"
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)
